In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
!pip install catboost
!pip install impyute
!pip install optuna
!pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
# package를 import 하는 방식으로 바꾸는게 좋다!!

# Data Wrangling
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

# Visualization
import matplotlib.pylab as plt
from matplotlib import font_manager, rc
import seaborn as sns
%matplotlib inline

# Preprocessing & Feature Engineering
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MaxAbsScaler
from sklearn.feature_selection import SelectPercentile
from impyute.imputation.cs import fast_knn
from sklearn.utils import all_estimators
from sklearn.metrics import r2_score,mean_squared_error
# from pycaret.classification import *

# Encoder

import category_encoders as ce
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# Hyperparameter Optimization
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

# Modeling
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.base import ClassifierMixin
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import optuna
from sklearn import ensemble
from sklearn import metrics
from sklearn import model_selection
# Evaluation
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

# Utility
import os
import time
import random
import warnings; warnings.filterwarnings("ignore")
from IPython.display import Image
import pickle
from tqdm import tqdm, tqdm_notebook
import platform
from itertools import combinations
from scipy.stats.mstats import gmean

#matplotlib 한글깨짐 지원
import platform

path = "c:/Windows/Fonts/malgun.ttf"
if platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system...')
rc('axes', unicode_minus=False) 

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


Unknown system...


### 1. 데이터불러오기

In [4]:
ID_train = pd.DataFrame({'custid': pd.read_csv('/content/drive/MyDrive/강민수+이효빈+한윤지/Input/X_train.csv', encoding='cp949').custid.unique()})
ID_test = pd.DataFrame({'custid': pd.read_csv('/content/drive/MyDrive/강민수+이효빈+한윤지/Input/X_test.csv', encoding='cp949').custid.unique()})
target = pd.read_csv('/content/drive/MyDrive/강민수+이효빈+한윤지/Input/y_train.csv', encoding='cp949').group

In [5]:
train = pd.read_csv('/content/drive/MyDrive/강민수+이효빈+한윤지/Input/진짜마지막_train.csv', encoding = "cp949")
test = pd.read_csv('/content/drive/MyDrive/강민수+이효빈+한윤지/Input/진짜마지막_test.csv', encoding = "cp949")

In [6]:
# cat_fea_tr = pd.read_csv('/content/drive/MyDrive/강민수+이효빈+한윤지/Input/catboost용cat피처_train.csv', encoding = "cp949")
# cat_fea_te = pd.read_csv('/content/drive/MyDrive/강민수+이효빈+한윤지/Input/catboost용cat피처_test.csv', encoding = "cp949")

In [7]:
# cat_fea_tr = cat_fea_tr.iloc[:,1:]

In [8]:
# cat_fea_te = cat_fea_te.iloc[:,1:]

In [9]:
# train = pd.concat([train,cat_fea_tr], axis = 1)
# test = pd.concat([test,cat_fea_te], axis = 1)

In [10]:
# cat_feq = ['sales_dayofweek','str_nm','brd_nm','corner_nm','pc_nm','part_nm','team_nm','buyer_nm']

## Tuning

In [11]:
import sklearn

In [12]:
sklearn.metrics.log_loss

<function sklearn.metrics._classification.log_loss>

In [13]:
# 학습데이터 70%, 평가데이터 30%로 데이터 분할
X_train, X_dev, y_train, y_dev = train_test_split(train, target, test_size=0.3, random_state=0)

In [14]:
cat_obj = CatBoostClassifier(iterations=100000, task_type = "GPU", learning_rate = 0.01, early_stopping_rounds = 100, random_state = 0)
# score = model_selection.cross_val_score(cat_obj, X_train, y_train, cv = 5, scoring = 'neg_log_loss')
# roc_auc = score.mean()
# cat_model = ('CatBoostClassifier', cat_obj, roc_auc)

In [15]:
cat_obj.fit(X_train, y_train, eval_set = (X_dev, y_dev))

0:	learn: 2.0683382	test: 2.0684045	best: 2.0684045 (0)	total: 149ms	remaining: 4h 8m 34s
1:	learn: 2.0581684	test: 2.0583391	best: 2.0583391 (1)	total: 241ms	remaining: 3h 20m 34s
2:	learn: 2.0478922	test: 2.0481890	best: 2.0481890 (2)	total: 331ms	remaining: 3h 3m 49s
3:	learn: 2.0376231	test: 2.0382069	best: 2.0382069 (3)	total: 392ms	remaining: 2h 43m 18s
4:	learn: 2.0277703	test: 2.0287010	best: 2.0287010 (4)	total: 456ms	remaining: 2h 31m 58s
5:	learn: 2.0184902	test: 2.0196388	best: 2.0196388 (5)	total: 518ms	remaining: 2h 23m 56s
6:	learn: 2.0092641	test: 2.0106602	best: 2.0106602 (6)	total: 584ms	remaining: 2h 19m 3s
7:	learn: 2.0005594	test: 2.0020581	best: 2.0020581 (7)	total: 649ms	remaining: 2h 15m 11s
8:	learn: 1.9923305	test: 1.9939942	best: 1.9939942 (8)	total: 715ms	remaining: 2h 12m 18s
9:	learn: 1.9845551	test: 1.9864460	best: 1.9864460 (9)	total: 781ms	remaining: 2h 10m 5s
10:	learn: 1.9763512	test: 1.9784594	best: 1.9784594 (10)	total: 846ms	remaining: 2h 8m 14s
11

In [16]:
cat_pred = cat_obj.predict_proba(X_dev)

In [17]:
cat_pred

array([[0.04660979, 0.61271226, 0.06361736, ..., 0.12732843, 0.08510707,
        0.01959929],
       [0.78405197, 0.09559862, 0.02070033, ..., 0.0246106 , 0.00990341,
        0.01274008],
       [0.77919066, 0.08951975, 0.0205479 , ..., 0.03274789, 0.00955986,
        0.01094095],
       ...,
       [0.73976788, 0.16293873, 0.02462093, ..., 0.02571415, 0.00927168,
        0.01345317],
       [0.64890329, 0.09477869, 0.03030611, ..., 0.12028392, 0.00824894,
        0.02681874],
       [0.06746585, 0.180573  , 0.15008609, ..., 0.22526409, 0.12063513,
        0.08257776]])

In [18]:
log_score = sklearn.metrics.log_loss(y_dev, cat_pred)

In [19]:
log_score

1.4597555024693083

In [20]:
# test 데이터 평가
preds_class = cat_obj.predict(test)
preds_proba = cat_obj.predict_proba(test)

In [21]:
print(preds_class)

[['M50']
 ['F40']
 ['F20']
 ...
 ['F20']
 ['F30']
 ['F20']]


In [22]:
print(preds_proba)

[[0.12111806 0.07788195 0.06451897 ... 0.15326599 0.03355237 0.2718285 ]
 [0.01787244 0.09920281 0.39348274 ... 0.03260848 0.37566638 0.04216111]
 [0.68407525 0.21011414 0.03261579 ... 0.02870798 0.00676953 0.00995517]
 ...
 [0.35170559 0.16662342 0.07551027 ... 0.12796611 0.02267335 0.06002335]
 [0.06052138 0.50844432 0.10298278 ... 0.23198093 0.06198628 0.00533584]
 [0.79090161 0.07583489 0.02633316 ... 0.0340625  0.01247678 0.00744209]]


In [23]:
ID_test

custid
0       30001
1       30002
2       30003
3       30005
4       30007
...       ...
14375   49988
14376   49990
14377   49992
14378   49993
14379   49994

[14380 rows x 1 columns]

In [24]:
ID_test = ID_test.custid

In [25]:
pred = pd.DataFrame(preds_proba)
pred.columns = ['F20', 'F30','F40','F50','M20', 'M30', 'M40', 'M50']
submissions = pd.concat([pd.Series(ID_test, name = 'ID'), pred], axis = 1)

In [26]:
submissions

ID       F20       F30       F40       F50       M20       M30  \
0      30001  0.121118  0.077882  0.064519  0.132201  0.145633  0.153266   
1      30002  0.017872  0.099203  0.393483  0.034598  0.004408  0.032608   
2      30003  0.684075  0.210114  0.032616  0.011856  0.015906  0.028708   
3      30005  0.538496  0.118013  0.037687  0.075717  0.023056  0.160361   
4      30007  0.906970  0.046900  0.007995  0.006373  0.017628  0.009211   
...      ...       ...       ...       ...       ...       ...       ...   
14375  49988  0.085952  0.443613  0.074181  0.028878  0.016463  0.204295   
14376  49990  0.430826  0.224944  0.113155  0.058949  0.028975  0.063275   
14377  49992  0.351706  0.166623  0.075510  0.117551  0.077947  0.127966   
14378  49993  0.060521  0.508444  0.102983  0.014640  0.014109  0.231981   
14379  49994  0.790902  0.075835  0.026333  0.008918  0.044031  0.034063   

            M40       M50  
0      0.033552  0.271828  
1      0.375666  0.042161  
2      0.006770  0.009955  
3      0.011552  0.035119  
4      0.002160  0.002763  
...         ...       ...  
14375  0.133615  0.013004  
14376  0.056814  0.023062  
14377  0.022673  0.060023  
14378  0.061986  0.005336  
14379  0.012477  0.007442  

[14380 rows x 9 columns]

In [28]:
submissions.to_csv('/content/drive/MyDrive/강민수+이효빈+한윤지/submission/cat_1.4597.csv', index = False)