In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install catboost
!pip install impyute
!pip install optuna
!pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 76.6 MB 163 kB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 308 kB 32.3 MB/s 
     |████████████████████████████████| 209 kB 12.4 MB/s 
     |████████████████████████████████| 81 kB 12.3 MB/s 
     |████████████████████████████████| 78 kB 8.6 MB/s 
     |████████████████████████████████| 146 kB 11.7 MB/s 
     |████████████████████████████████| 49 kB 7.2 MB/s 
     |████████████████████████████████| 112 kB 75.7 MB/s 
  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11137 sha256=e85b45920c5de1f20f5fcdc5f9b5751d9a544847f0561642a7425a1a2d97ed3d
  Stored in directory: /root/.cache/pip/wheels/9f/18/84/8f69f8b08169c7bae2dde6bd7daf0c19

In [ ]:
# package를 import 하는 방식으로 바꾸는게 좋다!!

# Data Wrangling
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

# Visualization
import matplotlib.pylab as plt
from matplotlib import font_manager, rc
import seaborn as sns
%matplotlib inline

# Preprocessing & Feature Engineering
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MaxAbsScaler
from sklearn.feature_selection import SelectPercentile
from impyute.imputation.cs import fast_knn
from sklearn.utils import all_estimators
from sklearn.metrics import r2_score,mean_squared_error
# from pycaret.classification import *

# Encoder

import category_encoders as ce
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# Hyperparameter Optimization
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

# Modeling
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.base import ClassifierMixin
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import optuna
from sklearn import ensemble
from sklearn import metrics
from sklearn import model_selection
# Evaluation
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

# Utility
import os
import time
import random
import warnings; warnings.filterwarnings("ignore")
from IPython.display import Image
import pickle
from tqdm import tqdm, tqdm_notebook
import platform
from itertools import combinations
from scipy.stats.mstats import gmean

#matplotlib 한글깨짐 지원
import platform

path = "c:/Windows/Fonts/malgun.ttf"
if platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system...')
rc('axes', unicode_minus=False) 

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


Unknown system...


### 1. 데이터불러오기

In [ ]:
ID_train = pd.DataFrame({'custid': pd.read_csv('/content/drive/MyDrive/머러컴피티션/X_train.csv', encoding='cp949').custid})
ID_test = pd.DataFrame({'custid': pd.read_csv('/content/drive/MyDrive/머러컴피티션/X_test.csv', encoding='cp949').custid})
target = pd.read_csv('/content/drive/MyDrive/머러컴피티션/y_train.csv', encoding = "cp949").group

In [ ]:
train = pd.read_csv('/content/drive/MyDrive/머러컴피티션/2등cat/snd_sum_shap_0615.csv')
test = pd.read_csv('/content/drive/MyDrive/머러컴피티션/2등cat/snd_sum_shap_te_0615.csv')

FileNotFoundError: ignored

In [ ]:
# cat = pd.read_csv('/content/drive/MyDrive/머러컴피티션/2등cat/catboost용cat피처_train.csv')
# cat_te = pd.read_csv('/content/drive/MyDrive/머러컴피티션/2등cat/catboost용cat피처_test.csv')

In [ ]:
# 학습데이터

In [ ]:
train = train.iloc[:,1:]

In [ ]:
test = test.iloc[:,1:]

In [ ]:
# cat_feq = ['sales_dayofweek','str_nm','brd_nm','corner_nm','pc_nm','part_nm','team_nm','buyer_nm']

## Tuning

In [ ]:
import sklearn

In [ ]:
sklearn.metrics.log_loss

<function sklearn.metrics._classification.log_loss>

In [ ]:
# 학습데이터 70%, 평가데이터 30%로 데이터 분할
X_train, X_dev, y_train, y_dev = train_test_split(train, target, test_size=0.3, random_state=0)

In [ ]:
cat_obj = CatBoostClassifier(iterations=20000, task_type = "GPU", learning_rate = 0.01, random_state = 0)
score = model_selection.cross_val_score(cat_obj, X_train, y_train, cv = 5, scoring = 'neg_log_loss')
roc_auc = score.mean()

cat_model = ('CatBoostClassifier', cat_obj, roc_auc)

Streaming output truncated to the last 5000 lines.
58939:	learn: 0.1635053	total: 19m 48s	remaining: 7m 4s
58940:	learn: 0.1634986	total: 19m 48s	remaining: 7m 4s
58941:	learn: 0.1634931	total: 19m 48s	remaining: 7m 4s
58942:	learn: 0.1634865	total: 19m 48s	remaining: 7m 4s
58943:	learn: 0.1634857	total: 19m 48s	remaining: 7m 4s
58944:	learn: 0.1634827	total: 19m 48s	remaining: 7m 4s
58945:	learn: 0.1634737	total: 19m 48s	remaining: 7m 4s
58946:	learn: 0.1634696	total: 19m 48s	remaining: 7m 4s
58947:	learn: 0.1634663	total: 19m 48s	remaining: 7m 4s
58948:	learn: 0.1634634	total: 19m 48s	remaining: 7m 4s
58949:	learn: 0.1634608	total: 19m 48s	remaining: 7m 4s
58950:	learn: 0.1634555	total: 19m 48s	remaining: 7m 4s
58951:	learn: 0.1634531	total: 19m 48s	remaining: 7m 4s
58952:	learn: 0.1634508	total: 19m 48s	remaining: 7m 4s
58953:	learn: 0.1634455	total: 19m 48s	remaining: 7m 4s
58954:	learn: 0.1634429	total: 19m 48s	remaining: 7m 4s
58955:	learn: 0.1634351	total: 19m 48s	remaining: 7m 

In [ ]:
cat_obj.fit(X_train, y_train, eval_set = (X_dev, y_dev), cat_features=cat_feq,early_stopping_rounds = 100)

In [ ]:
cat_pred = cat_obj.predict_proba(X_dev)

In [ ]:
cat_pred

In [ ]:
log_score = sklearn.metrics.log_loss(y_dev, cat_pred)

In [ ]:
log_score

In [ ]:
# test 데이터 평가
preds_class = cat_obj.predict(test)
preds_proba = cat_obj.predict_proba(test)

In [ ]:
print(preds_class)

[['M30']
 ['M40']
 ['F20']
 ...
 ['F20']
 ['F30']
 ['F20']]


In [ ]:
print(preds_proba)

[[0.08170172 0.10234136 0.0645409  ... 0.23809841 0.03772461 0.23337559]
 [0.02848102 0.13430051 0.35026064 ... 0.04401168 0.36058792 0.04156163]
 [0.68185011 0.20361806 0.03904366 ... 0.0275132  0.00681978 0.01243609]
 ...
 [0.39818536 0.13857493 0.0856322  ... 0.09283792 0.02303684 0.07272094]
 [0.06893821 0.43982213 0.10532218 ... 0.26310271 0.07978627 0.0078288 ]
 [0.77939985 0.07342787 0.02974799 ... 0.03654504 0.01644951 0.01095182]]


In [ ]:
ID_test

In [ ]:
ID_test = ID_test.custid

In [ ]:
pred = pd.DataFrame(preds_proba)
pred.columns = ['F20', 'F30','F40','F50','M20', 'M30', 'M40', 'M50']
submissions = pd.concat([pd.Series(ID_test, name = 'ID'), pred], axis = 1)

In [ ]:
submissions

ID       F20       F30       F40       F50       M20       M30  \
0      30001  0.081702  0.102341  0.064541  0.141317  0.100900  0.238098   
1      30002  0.028481  0.134301  0.350261  0.034487  0.006310  0.044012   
2      30003  0.681850  0.203618  0.039044  0.012865  0.015854  0.027513   
3      30005  0.578233  0.096668  0.045587  0.076608  0.026286  0.134382   
4      30007  0.908529  0.043037  0.009666  0.005423  0.016425  0.010444   
...      ...       ...       ...       ...       ...       ...       ...   
14375  49988  0.074377  0.477383  0.055493  0.021364  0.013025  0.212833   
14376  49990  0.384720  0.241054  0.126889  0.074380  0.026300  0.064299   
14377  49992  0.398185  0.138575  0.085632  0.123609  0.065403  0.092838   
14378  49993  0.068938  0.439822  0.105322  0.018399  0.016801  0.263103   
14379  49994  0.779400  0.073428  0.029748  0.010697  0.042781  0.036545   

            M40       M50  
0      0.037725  0.233376  
1      0.360588  0.041562  
2      0.006820  0.012436  
3      0.011806  0.030431  
4      0.003013  0.003462  
...         ...       ...  
14375  0.130510  0.015014  
14376  0.052983  0.029374  
14377  0.023037  0.072721  
14378  0.079786  0.007829  
14379  0.016450  0.010952  

[14380 rows x 9 columns]

In [ ]:
submissions.to_csv('/content/drive/MyDrive/머러컴피티션/2등cat/snd_sum_shap_0612_catsub2_1.4835 (1)', index = False)